apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: simongreen02/orion:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "MONGO_CONNECTION_URL"
        - name: SECRET_KEY
          value: "secret123"